get:
  operationId: getDepositContract
  summary: Get deposit contract address.
  description: Retrieve Eth1 deposit contract address and chain ID.
  tags:
    - Config
  responses:
    "200":
      description: Success
      content:
        application/json:
          schema:
            title: GetDepositContractResponse
            type: object
            required: [data]
            properties:
              data:
                type: object
                required: [chain_id, address]
                properties:
                  chain_id:
                    $ref: ../../beacon-node-oapi.yaml#/components/schemas/Uint64
                    description: Id of Eth1 chain on which contract is deployed.
                    example: "1"
                  address:
                    $ref: ../../beacon-node-oapi.yaml#/components/schemas/ExecutionAddress
                    description: Hex encoded deposit contract address with 0x prefix
                    example: "0x00000000219ab540356cBB839Cbe05303d7705Fa"
    "500":
      $ref: ../../beacon-node-oapi.yaml#/components/responses/InternalError
